name: Create Release and Publish to Mod Portal

on:
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  create-release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: npm run build
        run: npm run build
      - name: get mod version
        id: mod_version
        uses: ActionsTools/read-json-action@v1.0.5
        with:
          file_path: public/info.json
          prop_path: version
      - name: Install zip
        uses: montudor/action-zip@v0.1.1
      - name: Zip output
        run: zip -qq -r ../PeacefulTechTweaks_${{ steps.mod_version.outputs.value }}.zip PeacefulTechTweaks
        working-directory: dist
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "PeacefulTechTweaks_${{ steps.mod_version.outputs.value }}.zip"
          commit: main
          tag: v${{ steps.mod_version.outputs.value }}
          name: v${{ steps.mod_version.outputs.value }}
          body: Simple Seablock release v${{ steps.mod_version.outputs.value }}
      - name: Publish to Mod Portal
        uses: mchangrh/factorio-mod-upload@v1
        with:
          mod-name: PeacefulTechTweaks
        env:
          FACTORIO_MODS_TOKEN: ${{ secrets.FACTORIO_API_TOKEN }}
          FILENAME: ./PeacefulTechTweaks_${{ steps.mod_version.outputs.value }}.zip